In [251]:
import pandas as pd
import numpy as np

data = pd.read_csv("lastfm-matrix-germany.csv")

data1 = data[data.astype('bool').sum(axis=1)>10]
data1.drop("user", axis=1, inplace=True)
#this gives 138 columns instead of 195 for some reason
data1 = data1.replace(0,np.NaN)
data1 = data1.dropna(axis=1, thresh=35)

data1 = data1.fillna(0).astype(int)
data1

,ac/dc,adam green,air,amon amarth,amy macdonald,amy winehouse,apocalyptica,arctic monkeys,as i lay dying,atreyu,...,the rolling stones,the shins,the smashing pumpkins,the strokes,the subways,the white stripes,three days grace,timbaland,tool,u2
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1252,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1254,1,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1256,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [241]:
import scipy.spatial.distance as dist


artdists = dist.squareform(dist.pdist(data1.T,"cosine"))
distDf = pd.DataFrame(artdists)

columnames = list(data1.columns.values)
distDf.columns = columnames
distDf.index = columnames


distDf

,ac/dc,adam green,air,amon amarth,amy macdonald,amy winehouse,apocalyptica,arctic monkeys,as i lay dying,atreyu,...,the rolling stones,the shins,the smashing pumpkins,the strokes,the subways,the white stripes,three days grace,timbaland,tool,u2
ac/dc,0.000000,0.863426,0.929076,0.871813,0.981466,0.986204,0.820681,0.896257,0.898276,0.944397,...,0.803195,0.981688,0.963375,0.951095,0.911543,0.829534,0.961993,0.945063,0.928434,0.858468
adam green,0.863426,0.000000,0.901753,0.974633,1.000000,0.847112,1.000000,0.824354,0.976514,0.974325,...,0.950432,0.898531,0.923898,0.774181,0.877464,0.814463,0.947350,1.000000,0.900864,0.975493
air,0.929076,0.901753,0.000000,0.981557,0.981334,0.861057,0.950747,0.907127,1.000000,1.000000,...,0.891888,0.870901,0.870901,0.868658,0.964365,0.889635,0.961722,0.963114,0.891888,0.910913
amon amarth,0.871813,0.974633,0.981557,0.000000,0.975902,0.946188,0.872829,0.985013,0.823653,0.903607,...,1.000000,1.000000,1.000000,0.978805,0.976998,0.952506,0.925875,1.000000,0.906952,1.000000
amy macdonald,0.981466,1.000000,0.981334,0.975902,0.000000,0.745832,0.978548,0.908986,1.000000,1.000000,...,0.952912,0.951804,0.927706,0.914192,0.930157,0.951931,0.974992,0.975902,0.976456,0.953438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
the white stripes,0.829534,0.814463,0.889635,0.952506,0.951931,0.868806,0.957721,0.691079,0.985343,0.935908,...,0.891730,0.936675,0.841688,0.760421,0.816467,0.000000,0.967142,0.952506,0.891730,0.908234
three days grace,0.961993,0.947350,0.961722,0.925875,0.974992,0.925542,0.890024,0.968894,0.908498,0.824945,...,1.000000,0.975292,0.925875,0.956009,0.976130,0.967142,0.000000,0.876458,0.903439,0.952259
timbaland,0.945063,1.000000,0.963114,1.000000,0.975902,0.874438,0.978805,0.970025,0.933870,0.927706,...,0.953476,1.000000,0.976190,1.000000,1.000000,0.952506,0.876458,0.000000,0.953476,0.976998
tool,0.928434,0.900864,0.891888,0.906952,0.976456,0.964950,0.834337,0.912144,0.913854,0.929368,...,1.000000,0.953476,0.837165,0.917168,0.955053,0.891730,0.903439,0.953476,0.000000,0.955053
u2,0.858468,0.975493,0.910913,1.000000,0.953438,0.896025,0.918094,0.956563,0.978704,1.000000,...,0.820213,1.000000,0.953996,0.938570,0.933333,0.908234,0.952259,0.976998,0.955053,0.000000

In [249]:
#Drop lower half
def get_redundant_pairs(df):
    pairs_to_drop = set()
    cols = df.columns
    for i in range(0, df.shape[1]):
        for j in range(0, i+1):
            pairs_to_drop.add((cols[i], cols[j]))
    return pairs_to_drop

def get_top(df, n):
    sims = df.unstack()
    labels_to_drop = get_redundant_pairs(df)
    sims = sims.drop(labels=labels_to_drop).sort_values(ascending=False)
    return sims[0:n]

#This doesn't seem right
get_top(distDf, 100)

ensiferum        snow patrol                1.0
beck             paramore                   1.0
                 rise against               1.0
                 rihanna                    1.0
editors          pink                       1.0
                                           ...
black eyed peas  queens of the stone age    1.0
paramore         the rolling stones         1.0
                 the shins                  1.0
massive attack   paramore                   1.0
dredg            oasis                      1.0
Length: 100, dtype: float64

In [236]:
#Neither does this
#Don't know how to proceed
sol = (distDf.where(np.triu(np.ones(distDf.shape), k=1).astype(np.bool))
                 .stack()
                 .sort_values(ascending=False))
sol

ensiferum       snow patrol        1.000000
beck            paramore           1.000000
                rise against       1.000000
                rihanna            1.000000
editors         pink               1.000000
                                     ...
in extremo      schandmaul         0.524869
massive attack  portishead         0.522916
blink-182       sum 41             0.521286
schandmaul      subway to sally    0.485217
in extremo      subway to sally    0.440377
Length: 9453, dtype: float64